### ISSUE TITLE
Integrate with DBpedia docker images

### ISSUE THREAD

**Issue by jimkont** [AKSW/DBpedia-docker#1]
Hey Tim, is there a way to integrate this with the docker images offered by DBpedia?
https://github.com/dbpedia/Dockerized-DBpedia

if this is an improvement over that repo it would be in everyone's benefit to have a single docker image.

in terms of functionality, the other repo supports all languages + a version of the online endpoint and imho makes sense to merge efforts

**Comment by yamalight** [comment]
Hey Dimitris,

It's not really an improvement, just a different approach.

The approach used in Dockerized-DBpedia repo makes you build your own DBpedia container on your own system. Which might work for some people, but does take a whole lot of time (similar procedure took several days on a very powerful server for me).

The idea of this repo/container is to provide complete solution that can be started with one command without any additional actions/waiting times (aside from downloading ~50Gb of DBpedia data).
As you can see in README, you can get full working instance of core+en DBpedia backed by Virtuoso with this command: `docker run -p 8890:8890 -e DEFAULT_GRAPH=http://dbpedia.org -d aksw/dbpedia`.

**Comment by yamalight** [comment]
I'd say it's somewhat similar to [DBpedia AWS](https://aws.amazon.com/marketplace/pp/B012DSCFEK/) instance - preconfigured, deployable with 1 click/command.

**Comment by jimkont** [comment]
ok 

independent of that note that `/core/` contains an exact copy of the data in `dbpedia.org/sparql` (Except the ontology)
most of the files in `/core/` are in fact copies of files in `/core-i18n/en/`
files in `/core-i18n/en/` that are not in `/core/` are usually not so interesting to query except for special cases (like links between articles)

**Comment by yamalight** [comment]
@jimkont AFAIK my assembly is almost exactly the same as in Dockerized-DBpedia with language specified. I also used [this](https://joernhees.de/blog/2015/11/23/setting-up-a-linked-data-mirror-from-rdf-dumps-dbpedia-2015-04-freebase-wikidata-linkedgeodata-with-virtuso-7-2-1-and-docker-optional/) guide for reference.

**Comment by jimkont** [comment]
the download structure changed since that article
iirc the dockerized DBpedia downloads either a language or if you use `core` as language it downloads the contents of the `/core/` folder

**Comment by yamalight** [comment]
@jimkont hm, as far as I can tell from [this](https://github.com/dbpedia/Dockerized-DBpedia/blob/master/download.sh#L176) it does both too (if flag is provided).
do you have a link to a good up to date guide for building DBpedia?

**Comment by jimkont** [comment]
but this is only when 'core' is provided by the user
there is no new guide but the new structure is like this
- `{release}/core` -> data we have on the public endpoint, contains actually sym links to other files in the release
- `{release}/links` -> links to other datasets (copied in core/)
- `{release}/core-18n/{lang}` -> complete dumps for a language. most of the English files are in core/ as well as labels and abstracts from major languages

@neradis / @gone-phishing can also you verify?

**Comment by gone-phishing** [comment]
In case of Dockerized-DBpedia, we have taken into account the main '/core' endpoint along with the individual languages too. It's a generic framework (configurable/ deployable in 1 line only) which apart from downloading the datasets, does the bulk import to Virtuoso using the host system resources. This framework does the bulk import for the core directory before giving out the image. 

Since we can't generate separate images for all possible combinations of dump files across the languages available, our framework aims to solve this issue whereas this framework targets the core module. It certainly saves the time of doing bulk import to Virtuoso on the host system and so these images can exist independently.
