### ISSUE TITLE
How to run after build?

### ISSUE THREAD

**Issue by qwelias** [AKSW/DBpedia-docker#2]
I've [forked](https://github.com/qwemaze/DBpedia-docker) in order to modify language and virtuoso settings.
Finished build process and now have dbpedia tenforce/virtuoso container running left after `make virtuoso` command.
During build no docker images were created so instructions for running seems irrelevant.
I suppose I have to stop dbpedia container since `db` folder now populated and run tnforce/virtuoso with mounted `db` and some additional parameters.
Could you clarify?

**Comment by yamalight** [comment]
hi @qwemaze!
building produces usable virtuoso volume that you can just use when starting your own virtuoso instance - this will result in virtuoso starting with loaded dbpedia data.

**Comment by qwelias** [comment]
@yamalight 
So to sum it up:
Stop dbpedia container.
And execute
```
docker run --name dbpedia \
  -p 8890:8890 \
  -e DEFAULT_GRAPH=http://dbpedia.org \
  -v ${PWD}/db:/data \
  -v ${PWD}/virtuoso/virtuoso.ini:/data/virtuoso.ini \
  -d tenforce/virtuoso
```
Correct?

**Comment by yamalight** [comment]
@qwemaze yep, that should work
